spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=orderflow-super-secret-key-change-this-in-production-minimum-256-bits
jwt.expiration=86400000